version: '3'
services:
  test-mysql:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_USER: triangle
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'

  triangle-backend:
    depends_on:
      - test-mysql
    container_name: triangle-backend
    image: triangle-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      datasource.url: jdbc:mysql://test-mysql:3306/triangle?createDatabaseIfNotExist=true
      datasource.username: root
      datasource.password: 123456

