apiVersion: v2
name: triangle-app
description: A Helm chart for the Triangle Application
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Nuno Ferreira
    email: nunocardia21@gmail.com
    url: https://github.com/NunoCardia
dependencies:
  - name: mysql
    version: 9.4.8
    repository: https://charts.bitnami.com/bitnami
icon: https://i.pinimg.com/736x/06/ac/9d/06ac9da1a17c6daf308ea6b6bb6568a2.jpg

