apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{.Values.kubernetes.namespace}}
  labels:
    {{- include "triangle-app.labels" . | nindent 4 }}
data:
  datasource.url: jdbc:mysql://{{ .Values.mysql.fullnameOverride}}:{{ .Values.triangle_app.datasource.port}}/{{ .Values.mysql.auth.database}}?{{ .Values.triangle_app.datasource.params}}
  datasource.username: {{ .Values.mysql.auth.username}}