apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{.Values.kubernetes.namespace}}
  labels:
      {{- include "triangle-app.labels" . | nindent 4 }}
data:
  datasource.password: {{ .Values.mysql.auth.password | b64enc}}