apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{.Values.kubernetes.namespace}}
  labels:
    {{- include "triangle-app.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ .Chart.Name }}
  {{- with .Values.kubernetes.service}}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
  {{- end}}
      targetPort: http
      protocol: TCP
      name: http
